# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Paradis <adil.d.pro@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/18 19:07:51 by Paradis           #+#    #+#              #
#    Updated: 2024/08/19 21:18:57 by Paradis          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

42_EX00_PATH 			= 	./42/M00/ex00
42_EX00_BIN_PATH 		= 	./42/M00/ex00/bin
42_EX00_SRC_PATH		=	./42/M00/ex00/source
42_EX00_INC_PATH		=	./42/M00/ex00/include
42_EX00_UT_PATH			=	./42/M00/ex00/test
42_EX00_NAME			=	Megaphone
42_EX00_UT_SRC			=	$(42_EX00_UT_PATH)/$(42_EX00_NAME)_test.cpp
42_EX00_UT_NAME 		= 	test_$(42_EX00_NAME)
# # Files sources
42_EX00_SRC				=	$(42_EX00_SRC_PATH)/Megaphone.cpp \
							$(42_EX00_BIN_PATH)/main.cpp
# # Files object
42_EX00_OBJS			=	$(42_EX00_SRC:.cpp=.o)


EPITECH_EX00_PATH 		= 	./EPITECH/D06/ex00
EPITECH_EX00_BIN_PATH 	= 	./EPITECH/D06/ex00/bin
EPITECH_EX00_SRC_PATH	=	./EPITECH/D06/ex00/source
EPITECH_EX00_INC_PATH	=	./EPITECH/D06/ex00/include
EPITECH_EX00_UT_PATH	=	./EPITECH/D06/ex00/test
EPITECH_EX00_NAME		=	my_cat
EPITECH_EX00_UT_SRC		=	$(EPITECH_EX00_UT_PATH)/$(EPITECH_EX00_NAME)_test.cpp
EPITECH_EX00_UT_NAME 	= 	test_$(EPITECH_EX00_NAME)
# # Files sources
EPITECH_EX00_SRC		=	$(EPITECH_EX00_SRC_PATH)/MyCat.cpp \
							$(EPITECH_EX00_BIN_PATH)/main.cpp
							
EPITECH_EX00_FILE_TEST	=	$(EPITECH_EX00_UT_PATH)/D06_ex00_fileTest1.txt \
							$(EPITECH_EX00_UT_PATH)/D06_ex00_fileTest2.txt
# # Files object
EPITECH_EX00_OBJS		=	$(EPITECH_EX00_SRC:.cpp=.o)
##########################################################################
42_EX01_PATH 			= 	./42/M00/ex01
42_EX01_BIN_PATH 		= 	./42/M00/ex01/bin
42_EX01_SRC_PATH		=	./42/M00/ex01/source
42_EX01_INC_PATH		=	./42/M00/ex01/include
42_EX01_UT_PATH			=	./42/M00/ex01/test
42_EX01_NAME			=	PhoneBook
42_EX01_UT_SRC			=	$(42_EX01_UT_PATH)/$(42_EX01_NAME)_test.cpp
42_EX01_UT_NAME 		= 	test_$(42_EX01_NAME)
# # Files sources
42_EX01_SRC				=	$(42_EX01_SRC_PATH)/PhoneBook.cpp \
							$(42_EX01_SRC_PATH)/Contact.cpp \
							$(42_EX01_BIN_PATH)/main.cpp
# # Files object
42_EX01_OBJS			=	$(42_EX01_SRC:.cpp=.o)


EPITECH_EX01_PATH 		= 	./EPITECH/D06/ex01
EPITECH_EX01_BIN_PATH 	= 	./EPITECH/D06/ex01/bin
EPITECH_EX01_SRC_PATH	=	./EPITECH/D06/ex01/source
EPITECH_EX01_INC_PATH	=	./EPITECH/D06/ex01/include
EPITECH_EX01_UT_PATH	=	./EPITECH/D06/ex01/test
EPITECH_EX01_NAME		=	my_convert_temp
EPITECH_EX01_UT_SRC		=	$(EPITECH_EX01_UT_PATH)/$(EPITECH_EX01_NAME)_test.cpp
EPITECH_EX01_UT_NAME 	= 	test_$(EPITECH_EX01_NAME)
# # Files sources
EPITECH_EX01_SRC		=	$(EPITECH_EX01_SRC_PATH)/MyConvertTemp.cpp \
							$(EPITECH_EX01_BIN_PATH)/main.cpp
							
# # Files object
EPITECH_EX01_OBJS		=	$(EPITECH_EX01_SRC:.cpp=.o)
##########################################################################
42_EX02_PATH 			= 	./42/M00/ex02
42_EX02_NAME			=	test



EPITECH_EX02_PATH 		= 	./EPITECH/D06/ex02
EPITECH_EX02_BIN_PATH 	= 	./EPITECH/D06/ex02/bin
EPITECH_EX02_SRC_PATH	=	./EPITECH/D06/ex02/source
EPITECH_EX02_INC_PATH	=	./EPITECH/D06/ex02/include
EPITECH_EX02_UT_PATH	=	./EPITECH/D06/ex02/test
EPITECH_EX02_NAME		=	patient
EPITECH_EX02_UT_SRC		=	$(EPITECH_EX02_UT_PATH)/$(EPITECH_EX02_NAME)_test.cpp
EPITECH_EX02_UT_NAME 	= 	test_$(EPITECH_EX02_NAME)
# # Files sources
EPITECH_EX02_SRC		=	$(EPITECH_EX02_SRC_PATH)/SickKoala.cpp \
							$(EPITECH_EX02_BIN_PATH)/main.cpp
							
# # Files object
EPITECH_EX02_OBJS		=	$(EPITECH_EX02_SRC:.cpp=.o)
##########################################################################
EPITECH_EX03_PATH 		= 	./EPITECH/D06/ex03
EPITECH_EX03_BIN_PATH 	= 	./EPITECH/D06/ex03/bin
EPITECH_EX03_SRC_PATH	=	./EPITECH/D06/ex03/source
EPITECH_EX03_INC_PATH	=	./EPITECH/D06/ex03/include
EPITECH_EX03_UT_PATH	=	./EPITECH/D06/ex03/test
EPITECH_EX03_NAME		=	nurse
EPITECH_EX03_UT_SRC		=	$(EPITECH_EX03_UT_PATH)/$(EPITECH_EX03_NAME)_test.cpp
EPITECH_EX03_UT_NAME 	= 	test_$(EPITECH_EX03_NAME)
# # Files sources
EPITECH_EX03_SRC		=	$(EPITECH_EX03_SRC_PATH)/SickKoala.cpp \
							$(EPITECH_EX03_SRC_PATH)/KoalaNurse.cpp \
							$(EPITECH_EX03_BIN_PATH)/main.cpp
							
# # Files object
EPITECH_EX03_OBJS		=	$(EPITECH_EX03_SRC:.cpp=.o)
##########################################################################
EPITECH_EX04_PATH 		= 	./EPITECH/D06/ex04
EPITECH_EX04_BIN_PATH 	= 	./EPITECH/D06/ex04/bin
EPITECH_EX04_SRC_PATH	=	./EPITECH/D06/ex04/source
EPITECH_EX04_INC_PATH	=	./EPITECH/D06/ex04/include
EPITECH_EX04_UT_PATH	=	./EPITECH/D06/ex04/test
EPITECH_EX04_NAME		=	doctor
EPITECH_EX04_UT_SRC		=	$(EPITECH_EX04_UT_PATH)/$(EPITECH_EX04_NAME)_test.cpp
EPITECH_EX04_UT_NAME 	= 	test_$(EPITECH_EX04_NAME)
# # Files sources
EPITECH_EX04_SRC		=	$(EPITECH_EX04_SRC_PATH)/SickKoala.cpp \
							$(EPITECH_EX04_SRC_PATH)/KoalaNurse.cpp \
							$(EPITECH_EX04_SRC_PATH)/KoalaDoctor.cpp \
							$(EPITECH_EX04_BIN_PATH)/main.cpp
							
# # Files object
EPITECH_EX04_OBJS		=	$(EPITECH_EX04_SRC:.cpp=.o)
##########################################################################
EPITECH_EX05_PATH 		= 	./EPITECH/D06/ex05
EPITECH_EX05_BIN_PATH 	= 	./EPITECH/D06/ex05/bin
EPITECH_EX05_SRC_PATH	=	./EPITECH/D06/ex05/source
EPITECH_EX05_INC_PATH	=	./EPITECH/D06/ex05/include
EPITECH_EX05_UT_PATH	=	./EPITECH/D06/ex05/test
EPITECH_EX05_NAME		=	list
EPITECH_EX05_UT_SRC		=	$(EPITECH_EX05_UT_PATH)/$(EPITECH_EX05_NAME)_test.cpp
EPITECH_EX05_UT_NAME 	= 	test_$(EPITECH_EX05_NAME)
# # Files sources
EPITECH_EX05_SRC		=	$(EPITECH_EX05_SRC_PATH)/SickKoala.cpp \
							$(EPITECH_EX05_SRC_PATH)/KoalaNurse.cpp \
							$(EPITECH_EX05_SRC_PATH)/KoalaDoctor.cpp \
							$(EPITECH_EX05_SRC_PATH)/SickKoalaList.cpp \
							$(EPITECH_EX05_SRC_PATH)/KoalaNurseList.cpp \
							$(EPITECH_EX05_SRC_PATH)/KoalaDoctorList.cpp \
							$(EPITECH_EX05_BIN_PATH)/main.cpp
							
# # Files object
EPITECH_EX05_OBJS		=	$(EPITECH_EX05_SRC:.cpp=.o)
##########################################################################
EPITECH_EX06_PATH 		= 	./EPITECH/D06/ex06
EPITECH_EX06_BIN_PATH 	= 	./EPITECH/D06/ex06/bin
EPITECH_EX06_SRC_PATH	=	./EPITECH/D06/ex06/source
EPITECH_EX06_INC_PATH	=	./EPITECH/D06/ex06/include
EPITECH_EX06_UT_PATH	=	./EPITECH/D06/ex06/test
EPITECH_EX06_NAME		=	hospital
EPITECH_EX06_UT_SRC		=	$(EPITECH_EX06_UT_PATH)/$(EPITECH_EX06_NAME)_test.cpp
EPITECH_EX06_UT_NAME 	= 	test_$(EPITECH_EX06_NAME)
# # Files sources
EPITECH_EX06_SRC		=	$(EPITECH_EX06_SRC_PATH)/SickKoala.cpp \
							$(EPITECH_EX06_SRC_PATH)/KoalaNurse.cpp \
							$(EPITECH_EX06_SRC_PATH)/KoalaDoctor.cpp \
							$(EPITECH_EX06_SRC_PATH)/SickKoalaList.cpp \
							$(EPITECH_EX06_SRC_PATH)/KoalaNurseList.cpp \
							$(EPITECH_EX06_SRC_PATH)/KoalaDoctorList.cpp \
							$(EPITECH_EX06_SRC_PATH)/Hospital.cpp \
							$(EPITECH_EX06_BIN_PATH)/main.cpp
							
# # Files object
EPITECH_EX06_OBJS		=	$(EPITECH_EX06_SRC:.cpp=.o)
##########################################################################
# # Compilation and options compilation
G++ 					= 	g++
INCFLAGS				= 	-I
CPPFLAGS 				= 	-Wall -Wextra -Werror -W -Wfatal-errors -std=c++98



# # Default rule for compile all
all						:	$(42_EX00_NAME) \
							$(42_EX01_NAME) \
							$(EPITECH_EX00_NAME) \
							$(EPITECH_EX01_NAME) \
							$(EPITECH_EX02_NAME) \
							$(EPITECH_EX03_NAME) \
							$(EPITECH_EX04_NAME) \
							$(EPITECH_EX05_NAME) \
							$(EPITECH_EX06_NAME)

# # Rule for compiling all binaries
$(42_EX00_NAME)			: 	$(42_EX00_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(42_EX00_INC_PATH) $(42_EX00_OBJS) -o $(42_EX00_NAME)
$(42_EX01_NAME)			: 	$(42_EX01_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(42_EX01_INC_PATH) $(42_EX01_OBJS) -o $(42_EX01_NAME)

$(EPITECH_EX00_NAME)	: 	$(EPITECH_EX00_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(EPITECH_EX00_INC_PATH) $(EPITECH_EX00_OBJS) -o $(EPITECH_EX00_NAME)

$(EPITECH_EX01_NAME)	: 	$(EPITECH_EX01_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(EPITECH_EX01_INC_PATH) $(EPITECH_EX01_OBJS) -o $(EPITECH_EX01_NAME)

$(EPITECH_EX02_NAME)	: 	$(EPITECH_EX02_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(EPITECH_EX02_INC_PATH) $(EPITECH_EX02_OBJS) -o $(EPITECH_EX02_NAME)

$(EPITECH_EX03_NAME)	: 	$(EPITECH_EX03_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(EPITECH_EX03_INC_PATH) $(EPITECH_EX03_OBJS) -o $(EPITECH_EX03_NAME)

$(EPITECH_EX04_NAME)	: 	$(EPITECH_EX04_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(EPITECH_EX04_INC_PATH) $(EPITECH_EX04_OBJS) -o $(EPITECH_EX04_NAME)

$(EPITECH_EX05_NAME)	: 	$(EPITECH_EX05_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(EPITECH_EX05_INC_PATH) $(EPITECH_EX05_OBJS) -o $(EPITECH_EX05_NAME)

$(EPITECH_EX06_NAME)	: 	$(EPITECH_EX06_OBJS)
							$(G++) $(CPPFLAGS) $(INCFLAGS)$(EPITECH_EX06_INC_PATH) $(EPITECH_EX06_OBJS) -o $(EPITECH_EX06_NAME)
# $(NAME)					:	$(OBJS)
# 							$(G++) $(CPPFLAGS) $(OBJS) -o $(NAME) 
# # Default rules for Clean, Fclean and RM
CLEAN					=	clean
FCLEAN					=	fclean
RM						=	rm -rf

# # Rule compiling object files
clean					:	
							@$(MAKE) -s $(CLEAN) -C $(42_EX00_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(42_EX00_PATH)
							@$(MAKE) -s $(CLEAN) -C $(42_EX01_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(42_EX01_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX00_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX00_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX01_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX01_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX02_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX02_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX03_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX03_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX04_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX04_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX05_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX05_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX06_UT_PATH)
							@$(MAKE) -s $(CLEAN) -C $(EPITECH_EX06_PATH)
							

# # Rule compiling object files and binaries name
fclean					:	clean
							$(RM) $(42_EX00_NAME) $(42_EX01_NAME) $(42_EX02_PATH)/$(42_EX02_NAME) \
							$(EPITECH_EX00_NAME) $(EPITECH_EX01_NAME) $(EPITECH_EX02_NAME) $(EPITECH_EX03_NAME) \
							$(EPITECH_EX04_NAME) $(EPITECH_EX05_NAME) $(EPITECH_EX06_NAME)
							@$(MAKE) -s $(FCLEAN) -C $(42_EX00_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(42_EX00_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(42_EX01_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(42_EX01_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX00_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX00_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX01_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX01_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX02_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX02_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX03_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX03_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX04_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX04_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX05_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX05_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX06_UT_PATH)
							@$(MAKE) -s $(FCLEAN) -C $(EPITECH_EX06_PATH)
re						: 	clean fclean all
##########################################################################
####### SCHOOL 42 #######
##########################################################################
42_ex00 				: 	fclean
							@$(MAKE) -C $(42_EX00_PATH)
							$(42_EX00_PATH)/$(42_EX00_NAME)

42_ex01 				: 	fclean
							@$(MAKE) -C $(42_EX01_PATH)
							$(42_EX01_PATH)/$(42_EX01_NAME)

42_ex02 				: 	fclean
							cd ./42/M00/ex02/ && ./test.sh 42

42_test_run_ex00		:	fclean
							@$(MAKE) -s -C $(42_EX00_UT_PATH)
							$(42_EX00_UT_PATH)/$(42_EX00_UT_NAME)
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html
# @brave coverage.html

42_test_run_ex01		:	fclean
							@$(MAKE) -s -C $(42_EX01_UT_PATH)
							$(42_EX01_UT_PATH)/$(42_EX01_UT_NAME)
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html
##########################################################################
####### SCHOOL EPITECH #######
##########################################################################
EPITECH_ex00 			: 	fclean
							@$(MAKE) -C $(EPITECH_EX00_PATH)
							$(EPITECH_EX00_PATH)/$(EPITECH_EX00_NAME) $(EPITECH_EX00_FILE_TEST)

EPITECH_ex01 			: 	fclean
							@$(MAKE) -C $(EPITECH_EX01_PATH)
							$(EPITECH_EX01_PATH)/$(EPITECH_EX01_NAME)

EPITECH_ex02 			: 	fclean
							@$(MAKE) -C $(EPITECH_EX02_PATH)
							$(EPITECH_EX02_PATH)/$(EPITECH_EX02_NAME)

EPITECH_ex03 			: 	fclean
							cd $(EPITECH_EX03_PATH) && $(MAKE) && ./$(EPITECH_EX03_NAME)

EPITECH_ex04 			: 	fclean
							cd $(EPITECH_EX04_PATH) && $(MAKE) && ./$(EPITECH_EX04_NAME)

EPITECH_ex05 			: 	fclean
							cd $(EPITECH_EX05_PATH) && $(MAKE) && ./$(EPITECH_EX05_NAME)

EPITECH_ex06 			: 	fclean
							cd $(EPITECH_EX06_PATH) && $(MAKE) && ./$(EPITECH_EX06_NAME)

EPITECH_test_run_ex00	:	fclean
							@$(MAKE) -s -C $(EPITECH_EX00_UT_PATH)
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html

EPITECH_test_run_ex01	:	fclean
							@$(MAKE) -s -C $(EPITECH_EX01_UT_PATH)
							$(EPITECH_EX01_UT_PATH)/$(EPITECH_EX01_UT_NAME) --verbose
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html

EPITECH_test_run_ex02	:	fclean
							@$(MAKE) -s -C $(EPITECH_EX02_UT_PATH)
							$(EPITECH_EX02_UT_PATH)/$(EPITECH_EX02_UT_NAME) --verbose
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html

EPITECH_test_run_ex03	:	fclean
							cd $(EPITECH_EX03_UT_PATH) && $(MAKE) && ./$(EPITECH_EX03_UT_NAME) --verbose
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html

EPITECH_test_run_ex04	:	fclean
							cd $(EPITECH_EX04_UT_PATH) && $(MAKE) && ./$(EPITECH_EX04_UT_NAME) --verbose
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html

EPITECH_test_run_ex05	:	fclean
							cd $(EPITECH_EX05_UT_PATH) && $(MAKE) && ./$(EPITECH_EX05_UT_NAME) --verbose
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html

EPITECH_test_run_ex06	:	fclean
							cd $(EPITECH_EX06_UT_PATH) && $(MAKE) && ./$(EPITECH_EX06_UT_NAME) --verbose
							gcovr --exclude-unreachable-branches --exclude-throw-branches -r . --html --txt --html-details coverage.html
##########################################################################

# tests_run				:	fclean
# 							@$(MAKE) 42_test_run_ex00
# 							@echo "Press Enter to continue to the next test (ex01)..."
# 							@read dummy
# 							@echo "=====END====="
 
# .PHONY					: 	all clean fclean re \
# 							tests_run \
# 							Ex0 test_run_Ex0 \
# 							Ex1 test_run_Ex1 \
# 							Ex2 test_run_Ex2 \
# 							Ex3 test_run_Ex3 \
# 							Ex4 test_run_Ex4